service: baan-thai-backend

provider:
    name: aws
    runtime: nodejs22.x
    region: eu-north-1
    iam:
        role: ${env:IAM_ROLE_ARN}

    environment:
        TABLE_NAME: RestaurantTable

    httpApi:
        cors:
            allowedOrigins:
                - '*'
            allowedHeaders:
                - Content-Type
                - Authorization
            allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE

# as we create functions --> we need to add api endpoints to those functions

functions:
    #  -------------------USER---------------------
    handleRegister: # register as user or admin
        handler: functions/handleRegister.handler
        events:
            - httpApi:
                  path: /api/register
                  method: POST

    handleLogin: # logs in user or admin
        handler: functions/handleLogin.handler
        events:
            - httpApi:
                  path: /api/login
                  method: POST

    getUserProfile: # gets the userId's profile
        handler: functions/getUserProfile.handler
        events:
            - httpApi:
                  path: /api/profile/{userId}
                  method: GET

    #  -------------------MENU---------------------
    getMenu: # get all meals from the menu
        handler: functions/getMenu.handler
        events:
            - httpApi:
                  path: /api/menu
                  method: GET

    getProduct: # gets a single menu item
        handler: functions/getProduct.handler
        events:
            - httpApi:
                  path: /api/menu/{prodId}
                  method: GET

    createMenuItem: # add a new meal to menu
        handler: functions/createMenuItem.handler
        events:
            - httpApi:
                  path: /api/menu
                  method: POST

    updateMenuItem: # change a meal in menu
        handler: functions/updateMenuItem.handler
        events:
            - httpApi:
                  path: /api/menu/{prodId}
                  method: PUT

    deleteMenuItem: # removes menu product (menu item === a meal)
        handler: functions/deleteMenuItem.handler
        events:
            - httpApi:
                  path: /api/menu/{prodId}
                  method: DELETE

    #  -------------------ORDERS---------------------
    createOrder: # creates an order
        handler: functions/createOrder.handler
        events:
            - httpApi:
                  path: /api/orders
                  method: POST

    getAllOrders: # gets all orders
        handler: functions/getAllOrders.handler
        events:
            - httpApi:
                  path: /api/orders
                  method: GET

    getOrderbyUserId: # gets all orders by userId
        handler: functions/getOrdersByUserId.handler
        events:
            - httpApi:
                  path: /api/orders/{userId}
                  method: GET

    getOrdersByStatus: # gets all orders by status (pending, locked, completed)
        handler: functions/getOrdersByStatus.handler
        events:
            - httpApi:
                  path: /api/orders/status/{status}
                  method: GET

    updateOrderStatus: # change order status (pending, locked, complete)
        handler: functions/updateOrderStatus.handler
        events:
            - httpApi:
                  path: /api/orders/{orderId}/status
                  method: PUT

    cancelOrder: # userId cancels order
        handler: functions/cancelOrder.handler
        events:
            - httpApi:
                  path: /api/orders/{orderId}/cancel
                  method: PUT

    lockOrder: # admin locks order (no more edits by user can be done)
        handler: functions/lockOrder.handler
        events:
            - httpApi:
                  path: /api/orders/{orderId}/lock
                  method: PUT

    deleteOrder: # removes an order
        handler: functions/deleteOrder.handler
        events:
            - httpApi:
                  path: /api/orders/{orderId}
                  method: DELETE

    editOrder: # changes an order in case user did something wrong/forgot to add something
        handler: functions/editOrder.handler
        events:
            - httpApi:
                  path: /api/orders/{orderId}
                  method: PUT

    #  -------------------MESSAGES---------------------
    addOrderMessage: # add message to order's messages array
        handler: functions/addOrderMessage.handler
        events:
            - httpApi:
                  path: /api/orders/{orderId}/messages
                  method: POST

    #  -------------------PAYMENTS (MOCK)---------------------
    createPayment: # mock payment
        handler: functions/createPayment.handler
        events:
            - httpApi:
                  path: /api/orders/{orderId}/payment
                  method: POST

    #  -------------------CART---------------------
    getCart: # gets the userId's cart
        handler: functions/getCart.handler
        events:
            - httpApi:
                  path: /api/cart/{userId}
                  method: GET

    updateCart: # updates the userId's cart
        handler: functions/updateCart.handler
        events:
            - httpApi:
                  path: /api/cart/{userId}
                  method: PUT

    clearCart: # empties the userId's cart
        handler: functions/clearCart.handler
        events:
            - httpApi:
                  path: /api/cart/{userId}
                  method: DELETE
# resources:
#   Resources:
#     CloudDbTable:
#       Type: AWS::DynamoDB::Table
#       Properties:
#         TableName: RestaurantTable
#         AttributeDefinitions:
#           - AttributeName: PK
#             AttributeType: S
#           - AttributeName: SK
#             AttributeType: S
#           - AttributeName: categoryKey
#             AttributeType: S
#         KeySchema:
#           - AttributeName: PK
#             KeyType: HASH
#           - AttributeName: SK
#             KeyType: RANGE
#         GlobalSecondaryIndexes:
#           - IndexName: CategoryIndex
#             KeySchema:
#               - AttributeName: categoryKey
#                 KeyType: HASH
#               - AttributeName: SK
#                 KeyType: RANGE
#             Projection:
#               ProjectionType: ALL
#         BillingMode: PAY_PER_REQUEST

plugins:
    - serverless-dotenv-plugin
    - serverless-offline
